import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { CONFIG } from './config'
import { SerialManager } from './serial/SerialManager'
import type { SerialEvent, Source, TrialResult, TrialState } from './types'
import { stats } from './utils/stats'
import { exportCsv } from './utils/csv'

const fmt=(n:number)=>n.toFixed(1)
export default function App(){
  const serial=useMemo(()=>new SerialManager(),[]); const [state,setState]=useState<TrialState>('disconnected'); const [buttonDown,setButtonDown]=useState(false); const [source,setSource]=useState<Source>('hardware'); const [results,setResults]=useState<TrialResult[]>([]); const [error,setError]=useState(''); const [logs,setLogs]=useState<string[]>([]); const [debug,setDebug]=useState(false); const [stimulus,setStimulus]=useState<number|null>(null); const [lastArduino,setLastArduino]=useState<number|null>(null)
  const stateRef=useRef(state), buttonRef=useRef(buttonDown), stimulusRef=useRef<number|null>(null), timerRef=useRef<number|null>(null), rafRef=useRef<number|null>(null), trialToken=useRef(0), readyResolve=useRef<(()=>void)|null>(null)
  useEffect(()=>{stateRef.current=state},[state]); useEffect(()=>{buttonRef.current=buttonDown},[buttonDown])
  const log=useCallback((s:string)=>setLogs(x=>[`${performance.now().toFixed(3)}  ${s}`,...x].slice(0,CONFIG.maxLogLines)),[])
  const clearSchedule=useCallback(()=>{if(timerRef.current!==null)clearTimeout(timerRef.current);if(rafRef.current!==null)cancelAnimationFrame(rafRef.current);timerRef.current=rafRef.current=null},[])
  const record=useCallback((pressAt:number,micros:number|null,falseStart:boolean,valid=true,reason?:string)=>{setResults(xs=>[...xs,{trialNumber:xs.length+1,reactionTimeMs:falseStart||stimulusRef.current===null?null:Math.max(0,pressAt-stimulusRef.current),falseStart,stimulusTimestampMs:stimulusRef.current,pressReceivedTimestampMs:pressAt,arduinoPressMicros:micros,dateTime:new Date().toISOString(),source,valid,invalidReason:reason}])},[source])
  useLayoutEffect(()=>{if(state!=='go')return;rafRef.current=requestAnimationFrame(()=>{if(stateRef.current!=='go')return;const t=performance.now();stimulusRef.current=t;setStimulus(t);log(`GO paint timestamp ${t.toFixed(3)} ms`)});return()=>{if(rafRef.current!==null)cancelAnimationFrame(rafRef.current);rafRef.current=null}},[state,log])
  const onPress=useCallback((receivedAt:number,micros:number|null)=>{setButtonDown(true);setLastArduino(micros);if(stateRef.current==='waiting'){clearSchedule();record(receivedAt,micros,true);setState('false-start')}else if(stateRef.current==='go'){if(stimulusRef.current===null){record(receivedAt,micros,false,false,'Press arrived before a GO paint timestamp was available');setError('Trial invalidated because the GO frame was not confirmed as paint-ready.');setState('error')}else{record(receivedAt,micros,false);setState('result')}}},[clearSchedule,record])
  useEffect(()=>serial.onEvent((event:SerialEvent)=>{log(`< ${event.raw||event.message}`);if(event.type==='READY'){if(stateRef.current==='waiting'||stateRef.current==='go'){clearSchedule();record(event.receivedAt,null,false,false,'Arduino reset during trial');setError('Trial invalidated because the Arduino reset.');setState('error')}else{readyResolve.current?.();readyResolve.current=null;if(stateRef.current==='connecting'||stateRef.current==='error')setState('ready')}}else if(event.type==='PONG'){readyResolve.current?.();readyResolve.current=null;if(stateRef.current==='connecting'||stateRef.current==='error')setState('ready')}else if(event.type==='PRESS')onPress(event.receivedAt,event.micros??null);else if(event.type==='RELEASE')setButtonDown(false);else if(event.type==='ERROR'){clearSchedule();setError(event.message||'Arduino reported an error.');setState('error')}}),[serial,log,onPress,clearSchedule,record])
  useEffect(()=>{const hidden=()=>{if((document.hidden||!document.hasFocus())&&(stateRef.current==='waiting'||stateRef.current==='go')){clearSchedule();record(performance.now(),null,false,false,'Page hidden or lost focus during trial');setError('Trial invalidated because this page lost focus.');setState('error')}};document.addEventListener('visibilitychange',hidden);window.addEventListener('blur',hidden);return()=>{document.removeEventListener('visibilitychange',hidden);window.removeEventListener('blur',hidden)}},[clearSchedule,record])
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(source!=='simulator'||e.code!=='Space'||e.repeat||/INPUT|TEXTAREA|BUTTON/.test((e.target as HTMLElement).tagName))return;e.preventDefault();if(e.type==='keydown')onPress(performance.now(),null);else setButtonDown(false)};window.addEventListener('keydown',key);window.addEventListener('keyup',key);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',key)}},[source,onPress])
  useEffect(()=>()=>{clearSchedule();void serial.disconnect()},[serial,clearSchedule])
  async function connect(){setError('');setState('connecting');try{if(serial.isConnected())await serial.disconnect();await serial.connect();await new Promise<void>((resolve,reject)=>{const id=setTimeout(()=>reject(new Error('Timed out waiting for READY/PONG. The Nano may still be resetting; disconnect and try again.')),CONFIG.readyTimeoutMs);readyResolve.current=()=>{clearTimeout(id);resolve()};void serial.send('PING')})}catch(e){readyResolve.current=null;await serial.disconnect();setError(e instanceof Error?e.message:String(e));setState('error')}}
  async function disconnect(){clearSchedule();await serial.disconnect();setButtonDown(false);setState('disconnected')}
  async function start(){if(stateRef.current!=='ready'&&stateRef.current!=='result'&&stateRef.current!=='false-start')return;if(buttonRef.current){setError('Release the giant button before starting.');return}setError('');stimulusRef.current=null;setStimulus(null);const token=++trialToken.current;setState('waiting');try{if(source==='hardware')await serial.send('ARM')}catch(e){setError(e instanceof Error?e.message:String(e));setState('error');return}const delay=CONFIG.minDelayMs+Math.random()*(CONFIG.maxDelayMs-CONFIG.minDelayMs);timerRef.current=window.setTimeout(()=>{if(token!==trialToken.current||stateRef.current!=='waiting')return;setState('go')},delay)}
  function simulator(){clearSchedule();void serial.disconnect();setSource('simulator');setButtonDown(false);setError('');setState('ready')}
  const summary=stats(results);const last=results.at(-1)
  return <main className={`app state-${state}`}>
    <header><div className="brand"><span className="dot"/>GIANT BUTTON LAB</div><div className="status">{source==='simulator'?'SIMULATOR':state==='disconnected'?'OFFLINE':buttonDown?'BUTTON HELD':'BUTTON RELEASED'}</div></header>
    <section className="stage" aria-live="assertive">
      {state==='disconnected'&&<><p className="eyebrow">REACTION TIME TESTER</p><h1>Ready when<br/>you are.</h1><p>Connect the Arduino Nano, then hit the giant button the instant the screen turns green.</p><div className="actions"><button className="primary" onClick={connect}>Connect Arduino</button><button onClick={simulator}>Use keyboard simulator</button></div><small>Chrome or Edge on Windows · 115200 baud · switch on D2</small></>}
      {state==='connecting'&&<><p className="eyebrow">CONNECTING</p><h1>Finding the<br/>giant button…</h1><p>Select the Nano’s COM port in the browser prompt. It may reset once connected.</p></>}
      {(state==='ready'||state==='result'||state==='false-start')&&<>{state==='ready'&&<><p className="eyebrow">SYSTEM READY</p><h1>Fast hands?</h1><p>Keep the button released. The wait is random, so don’t anticipate it.</p></>}{state==='result'&&last&&<><p className="eyebrow">REACTION TIME</p><h1 className="number">{Math.round(last.reactionTimeMs!)}<span> ms</span></h1><p>Measured arrival time: {fmt(last.reactionTimeMs!)} ms {last.source==='simulator'&&'· simulated'}</p></>}{state==='false-start'&&<><p className="eyebrow">FALSE START</p><h1>TOO<br/>EARLY</h1><p>Release the button, then try again.</p></>}<button className="primary" disabled={buttonDown} onClick={start}>{buttonDown?'Release button':'Start trial'}</button></>}
      {state==='waiting'&&<><p className="eyebrow">WAIT FOR IT</p><h1>Hold<br/>steady.</h1><p>Pressing now is a false start.</p></>}
      {state==='go'&&<h1 className="go">GO!</h1>}
      {state==='error'&&<><p className="eyebrow">TRIAL STOPPED</p><h1>Something<br/>changed.</h1><p>{error}</p><div className="actions"><button className="primary" onClick={source==='hardware'?connect:()=>setState('ready')}>Recover</button>{source==='hardware'&&<button onClick={disconnect}>Disconnect</button>}</div></>}
    </section>
    <aside className="side"><h2>Session</h2>{summary?<div className="stats"><div><b>{summary.count}</b><span>valid</span></div><div><b>{fmt(summary.average)}</b><span>average ms</span></div><div><b>{fmt(summary.median)}</b><span>median ms</span></div><div><b>{fmt(summary.fastest)}</b><span>fastest ms</span></div><div><b>{fmt(summary.slowest)}</b><span>slowest ms</span></div><div><b>{summary.sd===null?'—':fmt(summary.sd)}</b><span>std dev ms</span></div></div>:<p className="muted">No valid trials yet.</p>}<p className="muted">{results.filter(r=>r.falseStart).length} false starts · {results.filter(r=>!r.valid).length} invalid</p><div className="side-actions"><button disabled={!results.length} onClick={()=>exportCsv(results)}>Export CSV</button><button disabled={!results.length} onClick={()=>setResults([])}>Clear</button>{source==='hardware'&&state!=='disconnected'&&<button onClick={disconnect}>Disconnect</button>}{source==='simulator'&&<button onClick={()=>{clearSchedule();setSource('hardware');setState('disconnected')}}>Use hardware</button>}</div><details open={debug} onToggle={e=>setDebug((e.currentTarget as HTMLDetailsElement).open)}><summary>Diagnostics</summary><dl><dt>State</dt><dd>{state}</dd><dt>Source</dt><dd>{source}</dd><dt>Button</dt><dd>{buttonDown?'pressed':'released'}</dd><dt>Stimulus</dt><dd>{stimulus?.toFixed(3)??'—'}</dd><dt>Arduino μs</dt><dd>{lastArduino??'—'}</dd></dl><pre>{logs.join('\n')||'No serial traffic.'}</pre></details></aside>
  </main>
}
